version: '3.8'

services:

  couchdb0:
    container_name: couchdb0
    image: couchdb:3.3

    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw

    ports:
      - "5984:5984"

    volumes:
      - ../volumes/couchdb0:/opt/couchdb/data

    networks:
      - coopnet


  couchdb1:
    container_name: couchdb1
    image: couchdb:3.3

    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw

    ports:
      - "6984:5984"

    volumes:
      - ../volumes/couchdb1:/opt/couchdb/data

    networks:
      - coopnet


  couchdb2:
    container_name: couchdb2
    image: couchdb:3.3

    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw

    ports:
      - "7984:5984"

    volumes:
      - ../volumes/couchdb2:/opt/couchdb/data

    networks:
      - coopnet


  couchdb3:
    container_name: couchdb3
    image: couchdb:3.3

    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw

    ports:
      - "8984:5984"

    volumes:
      - ../volumes/couchdb3:/opt/couchdb/data

    networks:
      - coopnet


networks:
  coopnet:
    name: coopnet